/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as TicketsConfirmRouteImport } from './routes/tickets.confirm'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdsIndexRouteImport } from './routes/_authenticated/ads/index'
import { Route as AuthenticatedAdsConfirmRouteImport } from './routes/_authenticated/ads/confirm'
import { Route as AuthenticatedOrganizerIndexRouteImport } from './routes/_authenticated/organizer/index'
import { Route as AuthenticatedOrganizerEventIdRouteImport } from './routes/_authenticated/organizer/$eventId'
import { Route as AuthenticatedOrganizerNewRouteImport } from './routes/_authenticated/organizer/new'
import { Route as AuthenticatedOrganizerPromoteRouteImport } from './routes/_authenticated/organizer/promote'
import { Route as AuthenticatedOrganizerScanRouteImport } from './routes/_authenticated/organizer/scan'
import { Route as ApiPublicCronSocialPublishRouteImport } from './routes/api/public/cron.social-publish'
import { Route as ApiPublicSocialCallbackProviderRouteImport } from './routes/api/public/social.callback.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsConfirmRoute = TicketsConfirmRouteImport.update({
  id: '/tickets/confirm',
  path: '/tickets/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsIndexRoute = AuthenticatedAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsConfirmRoute = AuthenticatedAdsConfirmRouteImport.update({
  id: '/ads/confirm',
  path: '/ads/confirm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizerIndexRoute =
  AuthenticatedOrganizerIndexRouteImport.update({
    id: '/organizer/',
    path: '/organizer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventIdRoute =
  AuthenticatedOrganizerEventIdRouteImport.update({
    id: '/organizer/$eventId',
    path: '/organizer/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerNewRoute =
  AuthenticatedOrganizerNewRouteImport.update({
    id: '/organizer/new',
    path: '/organizer/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerPromoteRoute =
  AuthenticatedOrganizerPromoteRouteImport.update({
    id: '/organizer/promote',
    path: '/organizer/promote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerScanRoute =
  AuthenticatedOrganizerScanRouteImport.update({
    id: '/organizer/scan',
    path: '/organizer/scan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronSocialPublishRoute =
  ApiPublicCronSocialPublishRouteImport.update({
    id: '/api/public/cron/social-publish',
    path: '/api/public/cron/social-publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialCallbackProviderRoute =
  ApiPublicSocialCallbackProviderRouteImport.update({
    id: '/api/public/social/callback/$provider',
    path: '/api/public/social/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/tickets/confirm': typeof TicketsConfirmRoute
  '/events/': typeof EventsIndexRoute
  '/ads/confirm': typeof AuthenticatedAdsConfirmRoute
  '/organizer/$eventId': typeof AuthenticatedOrganizerEventIdRoute
  '/organizer/new': typeof AuthenticatedOrganizerNewRoute
  '/organizer/promote': typeof AuthenticatedOrganizerPromoteRoute
  '/organizer/scan': typeof AuthenticatedOrganizerScanRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/ads/': typeof AuthenticatedAdsIndexRoute
  '/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/api/public/cron/social-publish': typeof ApiPublicCronSocialPublishRoute
  '/api/public/social/callback/$provider': typeof ApiPublicSocialCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/tickets/confirm': typeof TicketsConfirmRoute
  '/events': typeof EventsIndexRoute
  '/ads/confirm': typeof AuthenticatedAdsConfirmRoute
  '/organizer/$eventId': typeof AuthenticatedOrganizerEventIdRoute
  '/organizer/new': typeof AuthenticatedOrganizerNewRoute
  '/organizer/promote': typeof AuthenticatedOrganizerPromoteRoute
  '/organizer/scan': typeof AuthenticatedOrganizerScanRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ads': typeof AuthenticatedAdsIndexRoute
  '/organizer': typeof AuthenticatedOrganizerIndexRoute
  '/api/public/cron/social-publish': typeof ApiPublicCronSocialPublishRoute
  '/api/public/social/callback/$provider': typeof ApiPublicSocialCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/tickets/confirm': typeof TicketsConfirmRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/ads/confirm': typeof AuthenticatedAdsConfirmRoute
  '/_authenticated/organizer/$eventId': typeof AuthenticatedOrganizerEventIdRoute
  '/_authenticated/organizer/new': typeof AuthenticatedOrganizerNewRoute
  '/_authenticated/organizer/promote': typeof AuthenticatedOrganizerPromoteRoute
  '/_authenticated/organizer/scan': typeof AuthenticatedOrganizerScanRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/ads/': typeof AuthenticatedAdsIndexRoute
  '/_authenticated/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/api/public/cron/social-publish': typeof ApiPublicCronSocialPublishRoute
  '/api/public/social/callback/$provider': typeof ApiPublicSocialCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/events/$eventId'
    | '/tickets/confirm'
    | '/events/'
    | '/ads/confirm'
    | '/organizer/$eventId'
    | '/organizer/new'
    | '/organizer/promote'
    | '/organizer/scan'
    | '/admin/'
    | '/ads/'
    | '/organizer/'
    | '/api/public/cron/social-publish'
    | '/api/public/social/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/events/$eventId'
    | '/tickets/confirm'
    | '/events'
    | '/ads/confirm'
    | '/organizer/$eventId'
    | '/organizer/new'
    | '/organizer/promote'
    | '/organizer/scan'
    | '/admin'
    | '/ads'
    | '/organizer'
    | '/api/public/cron/social-publish'
    | '/api/public/social/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/events/$eventId'
    | '/tickets/confirm'
    | '/events/'
    | '/_authenticated/ads/confirm'
    | '/_authenticated/organizer/$eventId'
    | '/_authenticated/organizer/new'
    | '/_authenticated/organizer/promote'
    | '/_authenticated/organizer/scan'
    | '/_authenticated/admin/'
    | '/_authenticated/ads/'
    | '/_authenticated/organizer/'
    | '/api/public/cron/social-publish'
    | '/api/public/social/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  TicketsConfirmRoute: typeof TicketsConfirmRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicCronSocialPublishRoute: typeof ApiPublicCronSocialPublishRoute
  ApiPublicSocialCallbackProviderRoute: typeof ApiPublicSocialCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/confirm': {
      id: '/tickets/confirm'
      path: '/tickets/confirm'
      fullPath: '/tickets/confirm'
      preLoaderRoute: typeof TicketsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads/': {
      id: '/_authenticated/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AuthenticatedAdsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads/confirm': {
      id: '/_authenticated/ads/confirm'
      path: '/ads/confirm'
      fullPath: '/ads/confirm'
      preLoaderRoute: typeof AuthenticatedAdsConfirmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/': {
      id: '/_authenticated/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof AuthenticatedOrganizerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/$eventId': {
      id: '/_authenticated/organizer/$eventId'
      path: '/organizer/$eventId'
      fullPath: '/organizer/$eventId'
      preLoaderRoute: typeof AuthenticatedOrganizerEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/new': {
      id: '/_authenticated/organizer/new'
      path: '/organizer/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof AuthenticatedOrganizerNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/promote': {
      id: '/_authenticated/organizer/promote'
      path: '/organizer/promote'
      fullPath: '/organizer/promote'
      preLoaderRoute: typeof AuthenticatedOrganizerPromoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/scan': {
      id: '/_authenticated/organizer/scan'
      path: '/organizer/scan'
      fullPath: '/organizer/scan'
      preLoaderRoute: typeof AuthenticatedOrganizerScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/social-publish': {
      id: '/api/public/cron/social-publish'
      path: '/api/public/cron/social-publish'
      fullPath: '/api/public/cron/social-publish'
      preLoaderRoute: typeof ApiPublicCronSocialPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/callback/$provider': {
      id: '/api/public/social/callback/$provider'
      path: '/api/public/social/callback/$provider'
      fullPath: '/api/public/social/callback/$provider'
      preLoaderRoute: typeof ApiPublicSocialCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdsConfirmRoute: typeof AuthenticatedAdsConfirmRoute
  AuthenticatedOrganizerEventIdRoute: typeof AuthenticatedOrganizerEventIdRoute
  AuthenticatedOrganizerNewRoute: typeof AuthenticatedOrganizerNewRoute
  AuthenticatedOrganizerPromoteRoute: typeof AuthenticatedOrganizerPromoteRoute
  AuthenticatedOrganizerScanRoute: typeof AuthenticatedOrganizerScanRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdsIndexRoute: typeof AuthenticatedAdsIndexRoute
  AuthenticatedOrganizerIndexRoute: typeof AuthenticatedOrganizerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdsConfirmRoute: AuthenticatedAdsConfirmRoute,
  AuthenticatedOrganizerEventIdRoute: AuthenticatedOrganizerEventIdRoute,
  AuthenticatedOrganizerNewRoute: AuthenticatedOrganizerNewRoute,
  AuthenticatedOrganizerPromoteRoute: AuthenticatedOrganizerPromoteRoute,
  AuthenticatedOrganizerScanRoute: AuthenticatedOrganizerScanRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdsIndexRoute: AuthenticatedAdsIndexRoute,
  AuthenticatedOrganizerIndexRoute: AuthenticatedOrganizerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  TicketsConfirmRoute: TicketsConfirmRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicCronSocialPublishRoute: ApiPublicCronSocialPublishRoute,
  ApiPublicSocialCallbackProviderRoute: ApiPublicSocialCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
